language: python

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

before_install:
  - git clone https://github.com/piwik/piwik-package.git tmp/piwik-package

script:
 - 'shellcheck *.sh'
 - python tests.py

matrix:
  fast_finish: true
