language: python
python:
  "3.6"

# Use container-based infrastructure for quicker build start-up
sudo: false

before_install:
  - git clone https://github.com/piwik/piwik-package.git tmp/piwik-package
  - composer install

script:
 - 'shellcheck *.sh'
 - python tests.py

matrix:
  fast_finish: true
